### ISSUE TITLE
Error on Fedora 23

### ISSUE THREAD

**Issue by JPtheJP** [coddingtonbear/linux-push-to-talk#3]
Hi,

I can install the application on Fedora 23 with Python 2.7.10. When running it it gives:

``` $ ptt ```

```
Traceback (most recent call last):
  File "/usr/bin/ptt", line 9, in <module>
    load_entry_point('push-to-talk==1.0.4', 'console_scripts', 'ptt')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/push_to_talk-1.0.4-py2.7.egg/push_to_talk_app/application.py", line 35, in <module>
    class PushToTalk(gtk.StatusIcon):
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 64, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183 
```

Can you help?

**Comment by coddingtonbear** [comment]
I'm afraid not @JPtheJP; I haven't personally used this package in several years, and lots of things are probably broken on modern versions of Gnome.

Glancing at the specific error you received, thigh makes it look like either your python GTK bindings are not installed, or (more likely) the way you import GObject has changed sometime in the last five years.

Good luck, though!

Cheers!

**Comment by JPtheJP** [comment]
Hi @coddingtonbear 

Could you please update the realm of the project to clearly declare it as abandoned, unsupported and tell people interested in it to fork it to a new place if they want to fix/improve it?

That would be nice. Thank a lot for the quick answer!
Cheers.
