### ISSUE TITLE
Error on Pop!_OS 19.04

### ISSUE THREAD

**Issue by HenryFBP** [coddingtonbear/linux-push-to-talk#4]
I get the following stack trace when running either `ptt` or `python2 -m push_to_talk_app.application`.

```
henryfbp@pop-os:~$ python2 -m push_to_talk_app.application 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/push_to_talk-1.0.4-py2.7.egg/push_to_talk_app/application.py", line 35, in <module>
    class PushToTalk(gtk.StatusIcon):
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 72, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```

**Comment by coddingtonbear** [comment]
Sorry-- it has been an extremely long time since I last used this, so I can't offer direct help with figuring this out, but if you did find an answer, I'd be happy to merge a pull request.
